# AWS App Runner Terraform Configuration
# Generated by Galleon for test-fastapi
# Tier: Starter (App Runner - auto-scaling, scale-to-zero)

terraform {
  required_version = ">= 1.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    time = {
      source  = "hashicorp/time"
      version = "~> 0.9"
    }
  }
}

# Data source for current AWS account
data "aws_caller_identity" "current" {}
data "aws_region" "current" {}

# ECR Repository for container images
resource "aws_ecr_repository" "main" {
  name                 = var.name
  image_tag_mutability = "MUTABLE"
  force_delete         = true

  image_scanning_configuration {
    scan_on_push = true
  }

  tags = var.tags
}

# ECR Lifecycle Policy
resource "aws_ecr_lifecycle_policy" "main" {
  repository = aws_ecr_repository.main.name

  policy = jsonencode({
    rules = [
      {
        rulePriority = 1
        description  = "Keep last 10 images"
        selection = {
          tagStatus   = "any"
          countType   = "imageCountMoreThan"
          countNumber = 10
        }
        action = {
          type = "expire"
        }
      }
    ]
  })
}

# IAM Role for App Runner to access ECR
resource "aws_iam_role" "apprunner_ecr_access" {
  name = "${var.name}-apprunner-ecr-access"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "build.apprunner.amazonaws.com"
        }
      }
    ]
  })

  tags = var.tags
}

resource "aws_iam_role_policy_attachment" "apprunner_ecr_access" {
  role       = aws_iam_role.apprunner_ecr_access.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess"
}

# IAM Role for App Runner instance
resource "aws_iam_role" "apprunner_instance" {
  name = "${var.name}-apprunner-instance"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "tasks.apprunner.amazonaws.com"
        }
      }
    ]
  })

  tags = var.tags
}

# Auto Scaling Configuration
resource "aws_apprunner_auto_scaling_configuration_version" "main" {
  auto_scaling_configuration_name = "${var.name}-scaling"
  max_concurrency                 = var.max_concurrency
  max_size                        = var.max_capacity
  min_size                        = var.min_capacity

  tags = var.tags
}

# Local to determine if ECR image exists (for first deploy vs subsequent)
locals {
  # AWS's official hello-app-runner bootstrap image
  bootstrap_image = "public.ecr.aws/aws-containers/hello-app-runner:latest"
}

# Wait for IAM role propagation before creating App Runner service
resource "time_sleep" "iam_propagation" {
  depends_on      = [
    aws_iam_role.apprunner_ecr_access,
    aws_iam_role.apprunner_instance,
    aws_iam_role_policy_attachment.apprunner_ecr_access,
  ]
  create_duration = "15s"
}

# App Runner Service
resource "aws_apprunner_service" "main" {
  service_name = var.name

  source_configuration {
    # Only use ECR auth when using private ECR image
    dynamic "authentication_configuration" {
      for_each = var.use_ecr_image ? [1] : []
      content {
        access_role_arn = aws_iam_role.apprunner_ecr_access.arn
      }
    }

    image_repository {
      image_configuration {
        port = tostring(var.container_port)
        runtime_environment_variables = var.environment_variables
      }
      image_identifier      = var.use_ecr_image ? "${aws_ecr_repository.main.repository_url}:latest" : local.bootstrap_image
      image_repository_type = var.use_ecr_image ? "ECR" : "ECR_PUBLIC"
    }

    auto_deployments_enabled = false  # We control deployments via GitHub Actions
  }

  instance_configuration {
    cpu               = var.task_cpu
    memory            = var.task_memory
    instance_role_arn = aws_iam_role.apprunner_instance.arn
  }

  auto_scaling_configuration_arn = aws_apprunner_auto_scaling_configuration_version.main.arn

  health_check_configuration {
    protocol            = "HTTP"
    path                = var.use_ecr_image ? var.health_check_path : "/"
    interval            = 10
    timeout             = 5
    healthy_threshold   = 1
    unhealthy_threshold = 5
  }

  tags = var.tags

  depends_on = [
    time_sleep.iam_propagation
  ]
}
